// Copyright (c) 2025 Cloudflight. All rights reserved. 
export global Palette{
    out property <color> milk-color: #FDF8FF;
    out property <color> milk-shadow: #fdf8ff22;
    out property <color> water_color: #C09DF8;
    out property <color> water_shadow: #C09DF822;
    out property <color> background_dark: #112E59;
    out property <color> background_mid: #14468C;
    out property <color> background_light: #0053FF;
    out property <color> warn-color: #FFC700;
    out property <color> coffee-color: #FFA4BC;
    out property <color> coffee-shadow: #FFA4BC22;
    out property <color> espresso-color: #F3825F;
    out property <color> espresso-shadow: #F3825F22;
    out property <length> font_size_normal: 24px;
    out property <length> font_size_big: 32px;
    out property <length> font_size_large: 64px;
    out property <duration> animation-duration: 600ms;
}
